self.pushButton.clicked.connect(self.random_button)
self.pushButton_5.clicked.connect(self.random_button)
self.pushButton_7.clicked.connect(self.random_button)
self.clear_button.clicked.connect(self.clear_button_active)
self.pushButton_6.clicked.connect(self.clear_button_passive)
self.clear_button_2.clicked.connect(self.clear_button_ofr)
self.go_button.clicked.connect(self.collect_data)
self.go_button.clicked.connect(self.show_window_2)
self.checkBox.stateChanged.connect(self.checkBox_2.setChecked)
self.checkBox.stateChanged.connect(self.checkBox_3.setChecked)
self.checkBox_2.stateChanged.connect(self.checkBox.setChecked)
self.checkBox_2.stateChanged.connect(self.checkBox_3.setChecked)
self.checkBox_3.stateChanged.connect(self.checkBox.setChecked)
self.checkBox_3.stateChanged.connect(self.checkBox_2.setChecked)
self.checkBox.stateChanged.connect(self.click_checkbox)
self.checkBox_2.stateChanged.connect(self.click_checkbox)
self.checkBox_3.stateChanged.connect(self.click_checkbox)
self.stats = FinancialStatements()